name: Reference Discord Question

on:
  schedule:
    - cron: "0 14 */1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send random media from images folder
        env:
          WEBHOOK: ${{ secrets.TORU }}
        run: |
          # ======================================
          # Automatically load files from /images
          # ======================================

          FILES=(test/*)

          COUNT=${#FILES[@]}

          if [ "$COUNT" -eq 0 ]; then
            echo "No media files found."
            exit 0
          fi

          # Pick random file
          INDEX=$((RANDOM % COUNT))
          FILE="${FILES[$INDEX]}"

          echo "Selected file: $FILE"

          # Encode spaces for URL
          ENCODED_FILE=$(printf '%s\n' "$FILE" | sed 's/ /%20/g')

          RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/$ENCODED_FILE"

          echo "Raw URL: $RAW_URL"

          # Detect file type
          if [[ "$FILE" =~ \.(jpg|jpeg|png|webp|gif|jfif)$ ]]; then

            curl -X POST \
            -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"shitposting\",
                \"color\": 10181046,
                \"image\": {
                  \"url\": \"$RAW_URL\"
                }
              }]
            }" \
            "$WEBHOOK"

          else

            curl -L "$RAW_URL" -o mediafile

            curl -X POST \
            -F "payload_json={
              \"embeds\": [{
                \"title\": \"shitposting\",
                \"color\": 10181046
              }]
            }" \
            -F "file=@mediafile" \
            "$WEBHOOK"

          fi
