name: Reference Discord Question

on:
  schedule:
    - cron: "0 17 */1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send next post
        run: |
          # ======================================

          readarray -t REFERENCES << 'EOF'
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/The_Cake_is_a_Lie_(12521108583).jpg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/mikuwhite.jfif
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/silksong.png
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/tameyourdragon.jpg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/grimm.jpg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(1).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(2).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(3).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(4).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(5).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(6).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(7).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(8).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(9).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(10).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(11).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(12).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(13).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(14).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(15).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(16).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(17).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(18).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(19).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(20).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(21).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(22).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(23).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(24).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(25).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(26).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(27).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(28).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(29).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(30).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(31).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(32).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(33).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(34).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(35).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(36).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(37).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(38).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(39).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(40).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(41).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(42).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(43).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(44).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(45).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(46).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(47).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(48).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(49).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(50).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(51).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(52).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(53).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(54).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(55).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(56).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(57).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(58).jpeg
          media|https://raw.githubusercontent.com/Vincent6760/reference-webhook/main/images/shitposting%20(59).jpeg
          EOF

          # ======================================
          # DO NOT EDIT BELOW THIS LINE
          # ======================================

          if [ "${#REFERENCES[@]}" -eq 0 ]; then
            echo "No references found. Exiting."
            exit 0
          fi

          COUNT=${#REFERENCES[@]}

          # Pick random entry
          INDEX=$((RANDOM % COUNT))

          ENTRY="${REFERENCES[$INDEX]}"
          CONTENT="${ENTRY#*|}"

          # Detect file type
          if [[ "$CONTENT" =~ \.(jpg|jpeg|png|webp|gif|jfif)$ ]]; then

            curl -X POST \
            -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"shitposting\",
                \"color\": 10181046,
                \"image\": {
                  \"url\": \"$CONTENT\"
                }
              }]
            }" \
            ${{ secrets.TORU }}

          else

            curl -X POST \
            -H "Content-Type: application/json" \
            -d "{
              \"content\": \"$CONTENT\"
            }" \
            ${{ secrets.TORU }}

          fi
